/// Flutter icons Meals
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Meals
///      fonts:
///       - asset: fonts/Meals.ttf
///
/// 
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
///
import 'package:flutter/widgets.dart';

class Meals {
  Meals._();

  static const _kFontFam = 'Meals';
  static const String? _kFontPkg = null;

  static const IconData food = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
